language: go
go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.5"

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make all
  - make test

before_deploy:
  - pip install --user release-manager==0.4.1

deploy:
  skip_cleanup: true
  provider: script
  script: make release
  on:
    condition: '"${TRAVIS_GO_VERSION}" == "1.12.5"'
    tags: true

env:
  global:
  - secure: jnLv3kEz1UHNzSHi/sOUj4OMhNEwJZON80hITNzufS9ofOzdotrTC8jYIdGzzjGjoQiFL4aL0JZY5VfdMSD9RgxnBZzSq4OtRzS1jbVmwgkt97sj+QG5Ga2hEE2UoEp5jV1ZA/Av2cW8yIsfsrRTySlJy5igtvWSvbPDDyYw0fFtvxp9b8dylZ+Ygvs+24+zl/2VlDr2A4Gef87rTAXu4zkFi2nLFQU29CrLENrT9q48aQUOJvUiJg7kXPfDcHiF2OATtlLl5MCDZohsPp6cwy+A0zC5v1Fj17boW0QtcUth5iSF+J9I7GrJ+aV10meFec8+bdickkgKKOoEiKMswvNnuVu4TNxiD+a9XwBC1ybE+LoNcYvq4OWMbAWS8sQ/bdsn/KBBJDw24kqs53uV6hpPUCotoTPYPF188bkqDu/a711tTJ/1bPNZwRNMjFxOOl+rdOmZ1U0TmBq5J6ek4ZhvDxacAKvX10tRZ/Am8O85zLfFId+WITim3zSGbRVGmSE5sa4dkEf18q2iK0GHxb7BZTEQnzn0KYjC6XcI4mp2CSjktRLD9a1QexM9UOFi6NO0mZHESk1lF7y0j3QFvxbVcbuBvL4nKGOTfjLGCCYTnvzPTzVxuKcocCHr5DTFrAQu9q5Bs2tNKtJKXG59K7VJ5BhAhn2poQBHLrwf/g4=
  - secure: CnzBAqTDF8sqVonAwVS4xmUq/XtZYf7gql18D2PmLbibOvTCT3MRy2B5FEK7ikcOlJ8qS3z83mIn0Y1iYRxWdtd++SbsBrZAFjTe/PyYf2ZD0/gzi5LaWQegUckS/ljNWeOuPuOt+3B81FARKscwGEYbFNpNOoLQ+Hs2LEoLwCy6cybgxKHeu0SCGMchNUhDZF2AJbUH0bRwpxkAdyEE3ASLcWqYra56zEwxGeiKKxKD7TNhs5GIbLGwcgqVe0ezp7sWMPZqDKDxejcggLbQytZfQ712UY/AIImntSE04q6CBLyWyJmItYdPjg0YKfXQzan+qAPsDBtwGe5YH/xiUmvLGQsr1Y+EQeIV5eSKZRrSYH3hETiwfZ0pZQ7h4AftYyRQmVK96elUyD/Gcyp2u7ozoBhQLoYVJAtjsK7sNFC1ciAGBSDx/eXF0j/3lF0STu7QA88B70oB29BOf4HSw3GvTLUa7kMxb+2spOZ6uP9zonu+5AnJdTKAoC/zzqSySe2Bkc+4eemNsJzuOT7W3NYSpF4J6BliITkrxGm/midcQGHV9KQd8RDlUafKWAK16AnlTb9R3lts5/PeGHaXhjeVUzMoiKOFmH/vnr9Ii5XwQZ7pvO+/zpAr22m5OGN1bSKYTxzsRUV7EMH8jq+u6P2ZtvApmeqNy0HrAQSpE38=
