name: ci

on:
  push:
    branches:
    - '*'
    - '*/*'
    - '**'

jobs:
  test:
    name: Compile & Test
    strategy:
      matrix:
        go-version: ['1.26']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v7
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v7

    - name: Cache go modules
      uses: actions/cache@v6
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0

    - name: Test
      run: make test

    - name: Compile
      run: make all
